Repository Enigmatisms/AdaPT, pull requests merged in 2023-03, with the labels that each got.

#4 BDPT debug
  README.md
  bxdf/brdf.py
  bxdf/bsdf.py
  emitters/point.py
  inputs/csphere/balls-mono.xml
  inputs/csphere/balls-multi.xml
  inputs/csphere/big.xml
  inputs/csphere/single-ball.xml
  inputs/vpt/balls.xml
  inputs/vpt/volbox.xml
  la/geo_optics.py
  render.py
  renderer/bdpt.py
  renderer/path_utils.py
  renderer/vanilla_renderer.py
  sampler/general_sampling.py
  scene/obj_desc.py
  tracer/path_tracer.py
Labels: fix

#6 Transient rendering (basic) done
  README.md
  bxdf/medium.py
  emitters/abtract_source.py
  emitters/area.py
  emitters/point.py
  inputs/trans/cbox-point.xml
  render.py
  renderer/bdpt.py
  renderer/constants.py
  scene/xml_parser.py
  tracer/path_tracer.py
  tracer/tracer_base.py
Labels: enhancement, fix

#7 Update README.md
  README.md
Labels: documentation

#8 Transient debug and speed / memory optimzation for highly scattering medium
  .gitignore
  auto_test.sh
  bxdf/medium.py
  configs/tdom_sim.conf
  emitters/collimated.py
  inputs/meshes/cornell/bunny.obj
  render.py
  renderer/bdpt.py
  renderer/path_utils.py
  renderer/vpt.py
  requirements.txt
  run.sh
  scene/opts.py
  tracer/path_tracer.py
  tracer/tracer_base.py
  utils/tdom_analyze.py
Labels: enhancement, fix
